app1:
  image: lucasko/springboot
  volumes:
    - ~/.m2:/root/.m2  
    - $PWD:/opt
  ports:
    - 8081:8080
  environment:
    - REDIS_HOST=192.168.104.140
    - MYSQL_HOST=192.168.104.140
    - MYSQL_DB=mydb
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=1234

